// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyzxgbuvekqunffrqbbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5enhnYnV2ZWtxdW5mZnJxYmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjYyNzQsImV4cCI6MjA2ODE0MjI3NH0.9chc_koGwdEdxVRuuIVpnv42WDaNMaYQJLaYA1dMb_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});